server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: ${MLS_PATIENT_URL:http://localhost:8081/}
          predicates:
            - Path=/patients/**
        - id: note-service
          uri: ${MLS_NOTE_URL:http://localhost:8082/}
          predicates:
            - Path=/notes/**
        - id: risk-service
          uri: ${MLS_RISK_URL:http://localhost:8083/}
          predicates:
            - Path=/risks/**