server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081/
          predicates:
            - Path=/patients/**
management:
  endpoints:
    web:
      exposure:
        include: "*"