server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081/
          predicates:
            - Path=/patients/**
        - id: note-service
          uri: http://localhost:8082/
          predicates:
            - Path=/notes/**
        - id: risk-service
          uri: http://localhost:8083/
          predicates:
            - Path=/risks/**
management:
  endpoints:
    web:
      exposure:
        include: "*"