server:
  port: 8081
spring:
  application:
    name: patient-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patient_db
    username: root
    password: root
