server:
  port: 8082
spring:
  application:
    name: doctor-note-service
  data:
    mongodb:
      host: ${MLS_HOST_MONGO:localhost}
      database: ${MLS_DB_NAME_MONGO:MediLaboSolutionsProjet}
      port: ${MLS_MONGO_PORT:27017}